FROM mcr.microsoft.com/vscode/devcontainers/cpp:focal

RUN apt-get update &&\
    apt-get install -y cmake libfreeimage-dev libfreeimageplus-dev \
    qt5-default freeglut3-dev libxi-dev libxmu-dev liblua5.3-dev \
    lua5.3 doxygen graphviz graphviz-dev asciidoc

